name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd ./CISE_Repos/worksheets/worksheet2/cise_ass1a_worksheet2-frontend
        npm install

    - name: Run the tests
      run: |
        cd ./CISE_Repos/worksheets/worksheet2/cise_ass1a_worksheet2-frontend
        npm test

    - name: Build
      run: |
        cd ./CISE_Repos/worksheets/worksheet2/cise_ass1a_worksheet2-frontend
        npm run build
